### PR TITLE
Added a line of text and an emoji

### PR DESCRIPTION
**Pull request by tullyhansen**
That… was pretty easy!

### CODE REVIEW

**Comment by hugovk** [comment]
Thanks! 

You can now click the button to delete your `patch-1` branch, now you don't need it any more.

**Comment by hugovk** [comment]
Also, editing by clicking the most recent file in the main repo means you're always editing the most recent, and you don't have to worry about updating your fork from the main one, and best of all can stay away from git commands.

**Comment by tullyhansen** [comment]
Whoa, okay, lost me there. My changes got folded into your changes therefore I don't need my changes in my local copy because I can pull down yours again…???

**Comment by tullyhansen** [comment]
Yeah, I am not going near Terminal at the minute if I can help it.

**Comment by hugovk** [comment]
> My changes got folded into your changes therefore I don't need my changes in my local copy because I can pull down yours again…???

Yes.

Short version: Generally, just click to edit a file in the browser, send a PR. Done.

Long version in git language:

When you clicked the pen icon, it made a *fork* for you of my test repo. It also made a *branch* called `patch-1` (like a parallel copy) in your repo. (Branches are generally a good idea because it allows you to propose lots of different changes, which might not necessarily be compatible. But I wouldn't worry about branches when editing through the browser, it just does them automatically.) When you first saved the change, it made a *commit* (like a single save/revision).

You then proposed the change back to me in a *pull request*, this one. I clicked the *merge* button, which merged your commit back into my *master branch* (master is just the main one). In the meantime when you were editing, I could have also changed the same file. The merge would attempt to pull just your changed lines in, and keep mine. (Sometimes there's a *conflict*, if we both edited the same line, when git doesn't know whose line to take, so manual fixing it needed.)

Once your commit is merged, it's there in my repo. You don't need that branch. If you needed to maintain your own fork, you could merge my master branch back into yours. If you were doing code, you would need to update your own fork from time to time with the master of the *upstream* (the main repo). 

But if you're just editing docs in the browser, you don't need to maintain your own fork. If you go to the main repo, click the pen icon, it'll always give you the most recent version from that main repo, and fork from that.

(Hope that's not too complicated! Just pen -> commit -> propose!)

Feel free to ask more, or edit more and send more PRs on this repo!

**Comment by tullyhansen** [comment]
Thanks a bunch for the thorough explanation. I think I'm getting my head around it.

**Pull request merged**
